apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorten
spec:
  selector:
    matchLabels:
      app: shorten
  replicas: 3
  template:
    metadata:
      labels:
        app: shorten
    spec:
      containers:
        - name: shorten
          image: pr4j3sh/shorten:v1.0.7
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: shorten
          volumeMounts:
            - name: postgres-cert
              mountPath: "/usr/src/app/certs/"
              readOnly: true
          ports:
            - containerPort: 5000
      volumes:
        - name: postgres-cert
          secret:
            secretName: postgres-cert
---
apiVersion: v1
kind: Service
metadata:
  name: shorten
spec:
  selector:
    app: shorten
  type: ClusterIP
  ports:
    - name: shorten
      port: 5000
      targetPort: 5000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shorten-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shorten
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
